services:
    client:
        build: ./client
        image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPONAME}_client:latest
        ports:
            - "${CLIENT_PORT}:3000"
        depends_on:
            - server
        # environment:
        #     API_URL: "http://${SERVER_HOST}:${SERVER_PORT}"
        env_file:
            - .env
        networks:
            - bellerouze_chatbot_network

    server:
        build: ./server
        image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPONAME}_server:latest
        ports:
            - "${SERVER_PORT}:8000"
        # environment:
        #     MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/bellerouze_chatbot
        depends_on:
            - mongodb
        env_file:
            - .env
        networks:
            - bellerouze_chatbot_network

    mongodb:
        image: mongo:7
        restart: always
        ports:
            - "${MONGO_PORT}:27017"
        volumes:
            - bellerouze_chatbot_mongodb_data:/data/db
        env_file:
            - .env
        networks:
            - bellerouze_chatbot_network

    mongo-express:
        image: mongo-express:1.0.2-20
        restart: always
        ports:
            - "${MONGOEXPRESS_PORT}:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_USERNAME}
            ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
        depends_on:
            - mongodb
        env_file:
            - .env
        networks:
            - bellerouze_chatbot_network

volumes:
    bellerouze_chatbot_mongodb_data:
        external: true

networks:
    bellerouze_chatbot_network:
        external: true
